name: MyPy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install --upgrade -r requirements.txt
      - run: pip install --upgrade -r optional-requirements.txt
      - run: pip install --upgrade -r dev-requirements.txt
      - run: pip install "mypy~=1.4.1"
      - run: mypy $(git ls-files '*.py')
